### ISSUE TITLE
著者ページの実装

### ISSUE THREAD

**Issue by KaiseiYokoyama** [AmusementCreators/WebSite#45]
ref. https://maku77.github.io/hugo/taxonomy/template.html

cargo.tomlに

```toml
[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
```

で、記事に

```toml
authors = ["Hoge Hoge"]
```

と設定すれば、`/authors/hoge-hoge/`に記事が並ぶ
