### ISSUE TITLE
Hugo アップデート

### ISSUE THREAD

**Issue by KaiseiYokoyama** [AmusementCreators/WebSite#70]
ref. https://gohugo.io/news/0.60.0-relnotes/

- code fence ` ``` ` のハイライトがデフォルトでonになる
- markdownファイルに直接埋め込んだhtmlを有効にする場合、`config.toml`に以下の設定が必要

```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```
