### ISSUE TITLE
PullRequestを貰ったときのNetlifyのプレビューに未来の記事が表示されない

### ISSUE THREAD

**Issue by KaiseiYokoyama** [AmusementCreators/WebSite#91]
### 解決法
ref. https://www.jerriepelser.com/blog/netlify-hugo-future-previews/ 
`netlify.toml` に

```toml
[context.deploy-preview]
  command = "hugo --DF"
```

で、下書きと未来の記事が表示される
